### ISSUE TITLE
Streamline Console Text Color Formatting with ANSI Escape Codes

### ISSUE THREAD

**Issue by SharonIV0x86** [amansingh169/College-Management-System#1]
Upon reviewing the contents of the colors.hpp file, it appears that the current approach to printing colored text might be excessive for our needs. A more efficient solution involves integrating ANSI escape codes, which facilitate colored text output on both Windows and Linux platforms.

I have previously implemented ANSI escape codes for text color formatting in a similar project, which you can find [here](https://github.com/SharonIV0x86/BankingSystem2.0/blob/main/color.hpp). By assigning this task to me, I can streamline the process of printing colored text throughout our project using ANSI escape codes, thereby enhancing its simplicity and efficiency.

**Comment by amansingh169** [comment]
Hey Sharon 👋,

I reviewed your BankingSystem 2.0 project and the color.hpp file.
I was initially using ANSI escape codes for formatting the text colors but when I tried to run the program on git bash the escape codes were not working hence printing plain white text, to fix that I looked up on google and found a github repository which had a color.hpp that would work on git bash too, so I used that (ofcourse I cant write all that) instead of ANSI escape codes.

I am flexible for changes therefore im not closing this issue, I will hand you the task upon further conversation, if you have any suggestions, I'm all ears!
